export const MSG_LOAD_SUCCESS = "MSG_LOAD_SUCCESS";
export const MSG_BUY_SUCCESS = "MSG_BUY_SUCCESS";
export const MSG_UPDATE_SUCCESS = "MSG_UPDATE_SUCCESS";
export const MSG_DELTE_SUCCESS = "MSG_DELTE_SUCCESS";
